import React,{useState,useEffect} from 'react'
import { Loader,Card,FormField } from '../components'


const RenderCards = ({ data, title }) => {
  // using ? to safely access the length property of data if data is null it will return undefined insteade of throwing an error
  if (data?.length > 0)  {
    return data.map((post) => <Card key={post.id} {...post} />)
  }
  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
}

const Home = () => {
  const [loading, setLoading] = useState(true)
  const [allPosts, setAllPosts] = useState(null)
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
        <p className="mt-2 text-[#222328] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI MODEL</p>
      </div>
      <div className='mt-10'>
        {
          loading ? (
            <div className='flex justify-center item-center'>
              <Loader />
            </div>
          ) :(
            <></>
          )
        }
      </div>
    </section>
  )
}
export default Home

