import React,{useState,useEffect} from 'react'
import { Loader,Card,FormField } from '../components'


const RenderCards = ({ data, title }) => {
  // using ? to safely access the length property of data if data is null it will return undefined insteade of throwing an error
  if (data?.length > 0)  {
    return data.map((post) => <Card key={post.id} {...post} />)
  }
  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
}

const Home = () => {

  return (
    <section className="max-w-7xl mx-auto flex flex-col justify-center item-center text-center border border-transparent backdrop-blur-xl shadow-2xl rounded-md p-4">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">DALL·E API now available in public beta</h1>
        <p className="mt-2 text-[#222328] text-[14px] max-w-[500px] text-center mx-auto">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI MODEL</p>
      </div>
      <div className='mt-40'>
          <h2 className="font-extrabold text-[#222328] text-[24px]">Introduction</h2>
          {/* <div className='text-component mb-v mt-v max-w-container grid grid-cols-12'> */}
          <p className='mt-10 col-span-12 col-start-1 text-left mx-auto max-l-xl'>DALL·E’s flexibility allows users to create and edit 
            original images ranging from the artistic to the photorealistic. 
            DALL·E excels at following natural language descriptions so users can 
            plainly describe what they want to see. As our research evolves, we will continue 
            to bring the state of the art into the API, including advances in image quality, 
            latency, scalability, and usability.

          </p>
          {/* </div> */}
      </div>
      
      <div className='mt-20'>
          <img src="https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg" alt="DALL-E" className='w-full  object-cover rounded-lg'></img>
      </div> 
      <div className='mt-20'>
        <p className='col-span-12 col-start-1 text-left mx-auto max-l-xl'>
          Developers can now integrate DALL·E directly into their apps and products 
          through our API. More than 3 million people are already using DALL·E to extend their 
          creativity and speed up their workflows, generating over 4 million images a day. Developers 
          can start building with this same technology in a matter of minutes.
        </p>
      </div>
      <div className='mt-20'>
        <h3 className="font-extrabold text-[#222328] text-[16px]">Built-in Moderation</h3>
        <p className='mt-10 col-span-12 col-start-1 text-left mx-auto max-l-xl'>
        Incorporating the trust & safety lessons we’ve learned while deploying DALL·E to 3 million
         artists and users worldwide, developers can ship with confidence knowing that built-in mitigations—like
        filters for hate symbols and gore—will handle the challenging aspects of moderation. As a part of OpenAI’s 
        commitment to responsible deployment, we will continue to make trust & safety a top priority so that developers 
        can focus on building.
        </p>
      </div>
    </section>
  )
}
export default Home

